spring.application.name=setting_pr_1

# DATABASE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:./db_dev;MODE=MySQL
#h2db가 mysql 모드로 작동한다 .은 현재폴더, db가 현재 폴더에 저장 JDBC URL

spring.datasource.driverClassName=org.h2.Driver
#Driver Class
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# db테이블을 자동으로 만들어줌 (클래스를 기초로해서)